

[package]
name = "mz_rust"
version = "0.0.2"
authors = ["me <me@gmail.com>"]
edition = "2021"

[lib]
name = "mz_lib"
path = "src/mz_lib.rs"

[[bin]]
name = "mz_gen"
path = "src/mz_gen.rs"

[dependencies]
rand = "0.8.5"
